version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: codelens-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: navan
      POSTGRES_DB: codelens
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5-community
    container_name: codelens-neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/navan123
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1024m
    ports:
      - "7474:7474" # HTTP Web UI
      - "7687:7687" # Bolt protocol
    volumes:
      - neo4jdata:/data

volumes:
  pgdata:
  neo4jdata:
